added redis
DSRCorporation/express-generator pull request #2
Opened 2017-02-15 09:55 UTC by MRJCrunch

2017-02-15 10:09 UTC, fxlrnrpt requested changes

2017-02-15 10:09 UTC, keenondrums commented on generators/app/templates/app/libs/utils/redis.includeRedis-addon.js
> +    BPromise = require('bluebird');
We have an abstraction wrapping promises. Use it

2017-02-15 10:09 UTC, keenondrums commented on generators/app/templates/app/libs/initializers/redis.includeRedis-addon.js
> +var attempts = 50,
Move it to config

2017-02-15 10:09 UTC, keenondrums commented on generators/app/templates/app/libs/initializers/redis.includeRedis-addon.js
> +                    process.exit(1);
I'm not sure exiting right away is the best option

2017-02-15 11:29 UTC, MRJCrunch commented on generators/app/templates/app/libs/initializers/redis.includeRedis-addon.js
> +var attempts = 50,
Done

2017-02-15 12:55 UTC, fxlrnrpt requested changes

2017-02-15 12:55 UTC, keenondrums commented on generators/app/templates/app/libs/utils/redis.includeRedis-addon.js
> +    return await new Promise(function(resolve) {
await new promise.Promise

2017-02-15 13:12 UTC, MRJCrunch commented on generators/app/templates/app/libs/utils/redis.includeRedis-addon.js
> +    return await new Promise(function(resolve) {
done

2017-02-15 13:15 UTC, fxlrnrpt approved these changes

2017-02-15 14:34 UTC, fxlrnrpt approved these changes

2017-02-16 08:39 UTC, fxlrnrpt approved these changes

2017-02-19 17:37 UTC, merged